### PR TITLE
Pushing minor changes not specific to the Asuswrt-merlin branch, for …

### PR DESCRIPTION
**Pull request by 1951FDG**
Hi,

I finally finished the port to Asuswrt-merlin, this pull request however is for changes independent of this branch, some typo fixes, found another "stupidity" mac line, optimized `openpyn_options` so that no two spaces are present in arguments passed, some color fixes, also removed the `--management` passed to openvpn if `silent` is `True`

Now regarding my Asuswrt-merlin branch, https://github.com/1951FDG/openpyn-nordvpn/tree/RT-AC86U-E5F0

Maybe we can talk about if you want to incorporate it into your master branch or not, or maybe your own separate branch or have me keep it were it is. I am new to this, so your feedback is welcome.

What does this branch do, it offers two features:

1. Script run support, just like on Linux or Mac, etc
2. NVRAM write support, basically writes the configuration and the actual connection to the VPN can be done with one click from within the router's web interface

Later I will write an android app, and send one command by ssh to the router, basically writing to nvram, and then one a three clicks to connect to the VPN in the web interface (maybe even automate this, if i can figure out how to call the connect code)

The branch includes five (four) new files:

- api.py
- asus.py
- converter.py
- initd.py
- S23openpyn

I've had to extract the api calls to its own separate file, since I use it in `asus.py` and `initd.py`

My suggestion, would be that you separate the api calls to `api.py` for your master branch? It would make it easier to maintain my code branch and would make your code more modular.

Initd support is also added, router still uses initd. The `initd.py` is also kind of a cool as it parses arguments passed when prompted and also allows one extra prompt if user messes up, by replicating the arg parser in `openpyn.py`, therefore allowing no bogus arguments to be passed to it, maybe something you could also do for `systemd.py` if you wanted to...

`converter.py`, was based on the work: https://bitbucket.org/cnavalici/nordvpn-converter/overview
which helped me as I used it as a base to build my code modifications on... (this being my first real Python contribution)

### CODE REVIEW

**Comment by jotyGill** [comment]
Hi,
This is amazing work mate. Ah the beauty of open source. I posted this script here so that it could be useful to some. I am glad that you not only found it useful but are also adding features to it. Yes i would love to include these features into the master branch. Seems like there are many improvements in your branch. See, I am a complete noob to programming in general. Due to the multiple changes between the branches I am not sure how to easily merge them. I guess we will figure it out. Yes, separating the api calls to api.py would be a good idea.

**Comment by 1951FDG** [comment]
Hi,

Thanks!! You are a noob to programming, LOL, yet your code looks pretty good, it seems well organised! That's one of the first things that stumbled me, how well constructed and understandable the code base is even for someone who didn't do Python before.

Regarding the merge to the master branch, just looked at the code again, you see the thing is, the Asus router/s Linux distros (other DD-WRT too) don't allow writing to `/usr/share/openpyn/` but to `/opt/usr/share/openpyn/`.

What I can do to make the branch merge friendly is to change methods that use the paths to accept an extra argument, the base file path.

1. Set base_file_path once, depending if Linux is Asuswrt-merlin, use `/opt/usr/share/openpyn/` otherwise use `/usr/share/openpyn/`
3. Pass base_file_path as argument to methods that use this base path
5. For example, `def update_config_files(base_file_path):`

This will help with merging later on!

If you agree to this approach, I'll make the branch merge friendly by incorporating these changes. I will then also call the remaining api calls to `api.py`

**Comment by jotyGill** [comment]
Thanks :)
Sounds good.
Alternatively we could just move all the config files to /opt/openpyn. I found out Debian isn't letting Pip install files in /usr/share/ anymore, not sure if it lets it install them in /opt/. Same is with Mac isn't it? 
If it's more convenient why not.

**Comment by 1951FDG** [comment]
No problem, I think I'll have it ready soon, maybe even tomorrow. I guess the main advantage will be for users, they could modify one line of code, to change the base file path for the whole script.

**Comment by 1951FDG** [comment]
Done, let me know, if you want me to open a pull request!
https://github.com/1951FDG/openpyn-nordvpn/tree/RT-AC86U-E5F0

**Comment by jotyGill** [comment]
Awesome! :) yeah If you could send a pull request to my test branch, I'll try it out then push it to the master branch.

**Comment by 1951FDG** [comment]
Done!

**Pull request merged**
